language: java
jdk:
  - openjdk8
before_install:
  - export TZ='Asia/Shanghai'
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
#  - mvn clean test package jacoco:report coveralls:report -DrepoToken=$repoToken
  - mvn clean package cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    keep_history: true
    skip_cleanup: true
    script: bash travis_docker_push.sh
    on:
      branch: master
