version: '2.1'
services:
  platform-configuration:
    build: bookstore-microservices-platform-configuration
    ports:
      - 8888:8888

  platform-registry:
    build: bookstore-microservices-platform-registry
    ports:
      - 8761:8761

  platform-gateway:
    build: bookstore-microservices-platform-gateway
    ports:
      - 8080:8080

  domain-security:
    build: bookstore-microservices-domain-security
    ports:
      - 8301:8301

  domain-account:
    build: bookstore-microservices-domain-account
    ports:
      - 8401:8401

  domain-warehouse:
    build: bookstore-microservices-domain-warehouse
    ports:
      - 8501:8501

  domain-payment:
    build: bookstore-microservices-domain-payment
    ports:
      - 8601:8601
